### ISSUE TITLE
Result on combined restaurant dataset

### ISSUE THREAD

**Issue by YashButala** [xuuuluuu/Position-Aware-Tagging-for-ASTE#2]
I am trying to run the code on the data obtained by combining 14res, 15res, and 16res datasets into one single restaurant dataset. However, on this combined data, my 12 GB RAM gets fully occupied and the code stops execution. Can you provide the result over combined data as I need It for analyzing models?

**Comment by xuuuluuu** [comment]
Hi, Have you tried to run the code on CPU instead of GPU?
