### ISSUE TITLE
triplet_data Format

### ISSUE THREAD

**Issue by abhinav-bohra** [xuuuluuu/Position-Aware-Tagging-for-ASTE#3]
Hello, could you please point me to the script that was used to convert 'ASTE-Data-V2' data to 'triplet_data' format?

**Comment by xuuuluuu** [comment]
Hi, I tried to find it but I failed. 

From what I can recall, the script should contain a few loops to label each word according to the triplet results.

btw, we suggest using the 'ASTE-Data-V2' data for the ASTE task.
