### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'index' in call to _th_take

### ISSUE THREAD

**Issue by jurys22** [xuuuluuu/Position-Aware-Tagging-for-ASTE#4]
Hello, 
I'm following your readme on Win OS and I get this error. Any hints? I read around that I need to change the int to Long but I'm not sure where and which file. 
```
(JET) PS C:\Users\sp\.conda\envs\JET\Position-Aware-Tagging-for-ASTE> python jet_o.py
# of original triplets:  1460
# of triplets for current setup:  601
# of original triplets:  346
# of triplets for current setup:  346
# of original triplets:  543
# of triplets for current setup:  543
Map:  {'<START>': 0, 'O': 1, 's': 2, 'b': 3, 'e': 4, 'i': 5, '<STOP>': 6}
vocab2id:  2861
vocab size:  2861
reading the pretraing embedding: data/glove.840B.300d.txt
[Info] Use the pretrained word embedding to initialize: 2861 x 300
['<START>', 'O', 's', 'b', 'e', 'i', '<STOP>']
Capacity successfully set to: [83 10  3  2  3  3  3]
The max size:  83
#instances= 487
Touching ...
..........
Toucing Completes taking  81.15600061416626  seconds.
[] tensor(-inf)
['O', '<START>'] tensor(0.5778)
['O', 'O'] tensor(1.5546)
['s', 'O'] tensor(-0.3605)
['O', 's'] tensor(-1.1066)
['<STOP>', 'O'] tensor(-1.2451)
['s', '<START>'] tensor(0.3075)
['b', '<START>'] tensor(2.9103)
['i', '<START>'] tensor(-1.8127)
['O', 'b'] tensor(-0.1694)
['O', 'e'] tensor(-0.6851)
['s', 's'] tensor(-0.1793)
['s', 'e'] tensor(0.5894)
['b', 'O'] tensor(0.6963)
['b', 's'] tensor(-0.8922)
['b', 'e'] tensor(0.0064)
['e', 'b'] tensor(-0.8084)
['e', 'i'] tensor(-0.1822)
['i', 'b'] tensor(-0.5260)
['i', 'i'] tensor(-1.2019)
['<STOP>', 's'] tensor(1.4376)
['<STOP>', 'e'] tensor(1.5863)
['e', 'O'] tensor(0.5885)
Start Training...
Traceback (most recent call last):
  File "jet_o.py", line 138, in <module>
    model.learn(train_insts, num_iter, dev_insts, test_insts, optimizer_str, batch_size)
  File "C:\Users\sp\.conda\envs\JET\Position-Aware-Tagging-for-ASTE\triplet\hypergraph\NetworkModel.py", line 257, in learn
    label_score = self.forward(gold_network)
  File "C:\Users\sp\.conda\envs\JET\Position-Aware-Tagging-for-ASTE\triplet\hypergraph\NetworkModel.py", line 409, in forward
    return network.inside()
  File "C:\Users\sp\.conda\envs\JET\Position-Aware-Tagging-for-ASTE\triplet\hypergraph\TensorNetwork.py", line 59, in inside
    for_expr = torch.sum(torch.take(self.inside_scores, childrens_stage), 2)  # this line is same as the above two lines
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'index' in call to _th_take
```

**Comment by xuuuluuu** [comment]
Hi, I haven't tried to run the script on Windows. However, can I check the version of Pytorch and Transformers?

**Comment by jurys22** [comment]
- pytorch                   1.4.0           py3.7_cuda101_cudnn7_0    pytorch
- transformers              4.13.0                   pypi_0    pypi

**Comment by xuuuluuu** [comment]
Hi, I tried it again by setting up a new environment from scratch, but I cannot reproduce your error. I have also updated some of the package requirements based on the fresh trial. 

![image](https://user-images.githubusercontent.com/9879421/145838411-15462fcb-1ee7-4977-8ff1-9f62ba0334f4.png)



Are you able to try it on Linux? I don't have a windows system.

**Comment by jurys22** [comment]
Hi again, I am creating a VM for linux. Can you please share with me the minimum requirements to run it?

**Comment by xuuuluuu** [comment]
Hi, try to create a new environment with the below commands:

conda create -n JET python=3.7 anaconda
conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch

And then pip install the following packages:

termcolor
networkx=2.6.3
matplotlib
PYEVALB
sentencepiece
transformers

It should work. Please let me know if there are any errors.

**Comment by jurys22** [comment]
I've done this. I noticed that sentencepiece will cause a segmentation failure that I solved using version 0.1.91.
However, once I launch this on Linux the process is killed - I looked at the memory and it seems that this might be the issue.

What are the system requirements that you are using? Thank you very much for all this

**Comment by jurys22** [comment]
I've tried today using Google ColabPro with 25gb of RAM  NVIDIA T4 GPU but I run out of memory very fast :( 
I will wait for your reply on your system, maybe mine is not enough to run this

**Comment by xuuuluuu** [comment]
I tested the code on a Linux machine with 3 2080Ti GPUs (~12GB), and 300 GB RAM. I suggest using CPU to run the code, as the speed is comparable on GPU and you might have a larger RAM when working with CPU.
